"""Hierarchical feature encoder for schema-consistency benchmarks.

Builds an item x feature matrix from a branching process, following the
generative rule in McClelland, McNaughton & Lampinen (2020): a feature may be
introduced at any node and appear in that node's descendants, but never in
descendants of nodes in other branches. See ``docs/sections/schema_benchmark_design.md``.

The matrix is the object whose SVD *is* the hierarchy -- one singular dimension
per categorical split, with strength set by how much feature variance sits in
that branch, which is why higher-level distinctions are learned first. Rows are
L2-normalised by default so the vectors live on the unit-norm manifold that
``SymbolicDecoder`` and the symbolic pipeline's ``l2``/``quantized`` feedback
modes already assume; the raw binary matrix stays available as
``feature_matrix`` because the SVD analysis wants the unnormalised form.

Interface parity with ``SymbolicEncoder`` (``embeddings``, ``word_to_idx``,
``idx_to_word``, ``embedding_dim``, ``encode``) is deliberate: ``SymbolicDecoder``
works against this encoder unchanged.
"""
import numpy as np
from typing import Any, Dict, List, Optional, Sequence, Tuple, Union


# Recognised ``kind`` values for augment() specs, ordered by increasing
# inconsistency with the learned schema. See docs/sections/schema_benchmark_design.md S3.
NEW_ITEM_KINDS = ("duplicate", "within", "across", "random")


def _walk(spec: Any, name: str, level: int, parent: Optional[int],
          nodes: List[Dict[str, Any]]) -> int:
    """Depth-first build of the node table; returns the new node's index."""
    idx = len(nodes)
    nodes.append({"name": name, "level": level, "parent": parent,
                  "children": [], "leaves": [], "columns": []})
    if isinstance(spec, dict):
        for child_name, child_spec in spec.items():
            nodes[idx]["children"].append(_walk(child_spec, child_name, level + 1, idx, nodes))
    elif isinstance(spec, (list, tuple)):
        for leaf_name in spec:
            nodes[idx]["children"].append(_walk(None, leaf_name, level + 1, idx, nodes))
    return idx


def _balanced_spec(branching: Sequence[int], prefix: str = "n") -> Any:
    """Nested spec for a balanced tree with the given branching factors.

    ``branching=(2, 2, 2)`` yields 8 leaves under 3 levels of binary splits --
    the shape of the dataset in the paper (2 birds, 2 fish, 2 trees, 2 flowers).
    """
    counters = {"item": 0, "node": 0}

    def build(depth: int) -> Any:
        if depth == len(branching) - 1:
            leaves = []
            for _ in range(branching[depth]):
                leaves.append(f"item{counters['item']}")
                counters["item"] += 1
            return leaves
        out = {}
        for _ in range(branching[depth]):
            name = f"{prefix}{depth + 1}_{counters['node']}"
            counters["node"] += 1
            out[name] = build(depth + 1)
        return out

    return build(0)


class HierarchicalEncoder:
    """Item x feature encoder generated by a branching process.

    Construct with exactly one of ``tree`` (explicit nested spec) or
    ``branching`` (balanced factors per level).

    Args:
        tree: Nested spec. A dict maps a node name to its subtree; a list or
            tuple of strings is a node whose children are leaves. Example::

                {"animal": {"bird": ["sparrow", "hawk"],
                            "fish": ["salmon", "sunfish"]},
                 "plant":  {"tree": ["oak", "maple"],
                            "flower": ["rose", "daisy"]}}

        branching: Branching factor per level, e.g. ``(2, 2, 2)`` for 8 leaves.
            Names are generated; pass ``tree`` when readable names matter.
        features_per_node: How many new feature columns each node introduces.
            A uniform count is the regime in which the paper's prediction holds
            (one singular dimension per pairwise split); vary it to deliberately
            unbalance branch strength.
        include_root_features: Whether the root introduces features shared by
            every item. False by default, matching the paper, where the two
            top-level groups share no features at all.
        normalize: L2-normalise rows. Leave True for use with the models.
        seed: Reserved for ``augment``; the base matrix is deterministic.
    """

    def __init__(
        self,
        tree: Optional[Any] = None,
        branching: Optional[Sequence[int]] = None,
        features_per_node: int = 2,
        include_root_features: bool = False,
        normalize: bool = True,
        seed: Optional[int] = None,
        root_name: str = "root",
    ):
        if (tree is None) == (branching is None):
            raise ValueError("Provide exactly one of tree= or branching=.")
        if features_per_node < 1:
            raise ValueError("features_per_node must be >= 1.")

        spec = tree if tree is not None else _balanced_spec(branching)
        self.nodes: List[Dict[str, Any]] = []
        _walk(spec, root_name, 0, None, self.nodes)

        self.features_per_node = features_per_node
        self.include_root_features = include_root_features
        self.normalize = normalize
        self.seed = seed
        self.rng = np.random.default_rng(seed)

        # --- leaves become items, in depth-first order ---
        self.idx_to_word: List[str] = []
        self.word_to_idx: Dict[str, int] = {}
        for i, node in enumerate(self.nodes):
            if not node["children"]:
                node["item"] = len(self.idx_to_word)
                self.word_to_idx[node["name"]] = len(self.idx_to_word)
                self.idx_to_word.append(node["name"])
            else:
                node["item"] = None
        if len(self.idx_to_word) != len(set(self.idx_to_word)):
            raise ValueError("Duplicate leaf names in tree spec.")

        # --- propagate leaf sets upward ---
        for i in range(len(self.nodes) - 1, -1, -1):
            node = self.nodes[i]
            if node["item"] is not None:
                node["leaves"] = [node["item"]]
            else:
                acc: List[int] = []
                for c in node["children"]:
                    acc.extend(self.nodes[c]["leaves"])
                node["leaves"] = sorted(acc)

        # --- assign feature columns; the branch rule is enforced by
        #     construction, since a column is owned by exactly one node and is
        #     set only for that node's leaves ---
        n_col = 0
        for i, node in enumerate(self.nodes):
            if i == 0 and not include_root_features:
                continue
            node["columns"] = list(range(n_col, n_col + features_per_node))
            n_col += features_per_node

        self.n_features = n_col
        M = np.zeros((len(self.idx_to_word), n_col))
        for node in self.nodes:
            for col in node["columns"]:
                M[node["leaves"], col] = 1.0
        self.feature_matrix = M
        self.embeddings = self._normalize_rows(M) if normalize else M.copy()
        self.embedding_dim = n_col

        self.name_to_node = {n["name"]: i for i, n in enumerate(self.nodes)}

    # ------------------------------------------------------------------
    # basics
    # ------------------------------------------------------------------
    @staticmethod
    def _normalize_rows(M: np.ndarray) -> np.ndarray:
        norms = np.linalg.norm(M, axis=1, keepdims=True)
        norms[norms == 0] = 1.0
        return M / norms

    def encode(self, sequence: List[str]) -> np.ndarray:
        """Translate a list of item names into feature vectors, (len, dim)."""
        out = np.zeros((len(sequence), self.embedding_dim))
        for i, word in enumerate(sequence):
            if word not in self.word_to_idx:
                raise ValueError(f"Item '{word}' not in this hierarchy.")
            out[i] = self.embeddings[self.word_to_idx[word]]
        return out

    @property
    def items(self) -> List[str]:
        return list(self.idx_to_word)

    @property
    def categories(self) -> List[str]:
        """Names of the parent nodes of the leaves -- the finest grouping above
        items. Present for parity with ``SymbolicEncoder.categories``."""
        out = {self.nodes[n["parent"]]["name"]
               for n in self.nodes if n["item"] is not None and n["parent"] is not None}
        return sorted(out)

    def category_of(self, item: str) -> str:
        """Name of the item's parent node."""
        node = self.nodes[self.name_to_node[item]]
        if node["parent"] is None:
            raise ValueError(f"'{item}' has no parent.")
        return self.nodes[node["parent"]]["name"]

    def level_names(self, level: int) -> List[str]:
        return [n["name"] for n in self.nodes if n["level"] == level]

    def node_indicator(self, name: str) -> np.ndarray:
        """0/1 vector over items marking membership of this node's subtree."""
        v = np.zeros(len(self.idx_to_word))
        v[self.nodes[self.name_to_node[name]]["leaves"]] = 1.0
        return v

    def ancestors(self, item: str) -> List[str]:
        """Node names from the item's leaf up to the root, inclusive."""
        idx = self.name_to_node[item]
        out = []
        while idx is not None:
            out.append(self.nodes[idx]["name"])
            idx = self.nodes[idx]["parent"]
        return out

    def common_ancestor_level(self, a: str, b: str) -> int:
        """Level of the deepest node containing both items.

        The natural graded similarity axis for a hierarchy: larger means the two
        items diverge later and share more features. Unlike ``SymbolicEncoder``'s
        continuous ``category_variance`` this is discrete, set by tree depth.
        """
        anc_a, anc_b = self.ancestors(a), set(self.ancestors(b))
        for name in anc_a:
            if name in anc_b:
                return self.nodes[self.name_to_node[name]]["level"]
        raise ValueError("Items share no ancestor (malformed tree).")

    # ------------------------------------------------------------------
    # structure analysis
    # ------------------------------------------------------------------
    def svd(self, normalized: bool = False) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """SVD of the item x feature matrix. Defaults to the raw binary matrix,
        which is the form the paper's analysis uses."""
        M = self.embeddings if normalized else self.feature_matrix
        return np.linalg.svd(M, full_matrices=False)

    def dimension_alignment(self, normalized: bool = False, tol: float = 1e-9
                            ) -> List[Dict[str, Any]]:
        """Match each singular dimension to the tree structure it encodes.

        For every dimension we score its item-classifying vector ``u_i`` against
        two families of candidate patterns built from the tree:

          * ``group``    -- the indicator of a single node's subtree
          * ``contrast`` -- the signed difference between two sibling subtrees

        and report the best match by absolute cosine. This measures, rather than
        assumes, the paper's claim that one dimension corresponds to one
        categorical split.

        Alignment is exact (1.0) only where splits are **binary**. An N-way split
        requires N-1 dimensions, and inside that degenerate subspace the singular
        values tie, so the basis the SVD returns is arbitrary and no individual
        dimension matches a single sibling contrast. The subspace is still
        correct -- those dimensions span the within-category contrasts -- so read
        per-dimension alignment only for levels with binary branching, and check
        the leaf level at the subspace level instead (see
        ``tests/test_hierarchical_encoder.py``).
        """
        U, S, _ = self.svd(normalized=normalized)
        candidates: List[Tuple[str, str, np.ndarray]] = []
        for i, node in enumerate(self.nodes):
            if node["parent"] is None and not self.include_root_features:
                continue
            candidates.append(("group", node["name"], self.node_indicator(node["name"])))
        for node in self.nodes:
            kids = node["children"]
            for a in range(len(kids)):
                for b in range(a + 1, len(kids)):
                    na, nb = self.nodes[kids[a]]["name"], self.nodes[kids[b]]["name"]
                    vec = self.node_indicator(na) - self.node_indicator(nb)
                    candidates.append(("contrast", f"{na}|{nb}", vec))

        out = []
        for d in range(U.shape[1]):
            u = U[:, d]
            if np.linalg.norm(u) < tol:
                continue
            best = None
            for kind, name, vec in candidates:
                nv = np.linalg.norm(vec)
                if nv < tol:
                    continue
                score = abs(float(np.dot(u, vec) / (np.linalg.norm(u) * nv)))
                if best is None or score > best[0]:
                    best = (score, kind, name)
            out.append({
                "dimension": d,
                "singular_value": float(S[d]),
                "match_kind": best[1],
                "match_node": best[2],
                "alignment": best[0],
                "level": self._match_level(best[2]),
            })
        return out

    def _match_level(self, match_name: str) -> Optional[int]:
        name = match_name.split("|")[0]
        idx = self.name_to_node.get(name)
        return None if idx is None else self.nodes[idx]["level"]

    def projection_ratio(self, vector: np.ndarray, rank: Optional[int] = None,
                         tol: float = 1e-9) -> float:
        """Fraction of ``vector``'s energy lying in the existing feature basis.

        This is the paper's operational definition of schema consistency: a new
        item is consistent to the extent that it projects onto the singular
        dimensions already present, and inconsistent to the extent that it
        demands a new one. Model-free -- it scores the *stimulus*, so the
        consistency ladder can be verified before any model is run.
        """
        _, S, Vt = self.svd()
        if rank is None:
            rank = int(np.sum(S > tol))
        basis = Vt[:rank]                       # (rank, n_features), orthonormal rows
        v = np.asarray(vector, dtype=float)
        if v.shape[0] < basis.shape[1]:         # augmented vector, base basis
            v = np.pad(v, (0, basis.shape[1] - v.shape[0]))
        elif v.shape[0] > basis.shape[1]:
            v = v[:basis.shape[1]]
        denom = float(np.dot(v, v))
        if denom < tol:
            return 0.0
        proj = basis @ v
        return float(np.dot(proj, proj) / denom)

    # ------------------------------------------------------------------
    # new items
    # ------------------------------------------------------------------
    def augment(self, specs: Sequence[Dict[str, Any]], seed: Optional[int] = None
                ) -> "HierarchicalEncoder":
        """Return a new encoder with extra items appended, at graded consistency.

        Each spec is ``{"name": str, "kind": one of NEW_ITEM_KINDS, ...}``:

          * ``duplicate``  -- copy ``target``'s shared features. All of its
            structure already exists in the schema.
          * ``within``     -- inherit the ancestor columns of ``parent`` and mix
            distinguishing columns drawn from *within* that subtree. The
            paper's sparrowhawk: a novel recombination that still respects the
            branch rule.
          * ``across``     -- inherit ancestor columns of ``parent`` but take
            distinguishing columns from ``other``, a node in a different branch.
            The paper's penguin; violates the generative rule.
          * ``random``     -- columns drawn uniformly at random across the whole
            feature space. No projection onto the schema at all.

        Every new item also receives its own unique identifying column, as every
        base item has. Note this means ``duplicate`` is not the paper's exact
        zero-new-dimension case: in a same-space ``predict_next`` setting items
        must be distinguishable to be predicted at all, so the weakest rung we
        can realise is "all shared structure known, identity feature new". The
        deviation is recorded in docs/sections/schema_benchmark_design.md S5.

        Active-feature counts are matched to the base mean so that consistency is
        not confounded with vector sparsity or norm.
        """
        rng = np.random.default_rng(self.seed if seed is None else seed)
        base_M = self.feature_matrix
        n_base_items, n_base_cols = base_M.shape
        target_density = float(np.mean(np.sum(base_M > 0, axis=1)))

        new_rows: List[np.ndarray] = []
        new_names: List[str] = []
        for spec in specs:
            kind = spec.get("kind")
            if kind not in NEW_ITEM_KINDS:
                raise ValueError(f"kind must be one of {NEW_ITEM_KINDS}, got {kind!r}")
            name = spec["name"]
            if name in self.word_to_idx or name in new_names:
                raise ValueError(f"Item name '{name}' already exists.")
            row = np.zeros(n_base_cols)

            if kind == "duplicate":
                row = base_M[self.word_to_idx[spec["target"]]].copy()

            elif kind == "within":
                parent = spec["parent"]
                row[self._ancestor_columns(parent)] = 1.0
                siblings = self.nodes[self.name_to_node[parent]]["leaves"]
                row = self._fill_across_sources(row, siblings, target_density, rng)

            elif kind == "across":
                parent, other = spec["parent"], spec["other"]
                row[self._ancestor_columns(parent)] = 1.0
                foreign = self.nodes[self.name_to_node[other]]["leaves"]
                row = self._fill_across_sources(row, foreign, target_density, rng)

            else:  # random
                row = self._fill_to_density(row, list(range(n_base_cols)),
                                            target_density, rng)

            new_rows.append(row)
            new_names.append(name)

        # Unique identifying columns, one block per new item. Base rows are
        # zero there, so their normalised embeddings are bit-identical.
        n_new = len(new_rows)
        extra = self.features_per_node * n_new
        M = np.zeros((n_base_items + n_new, n_base_cols + extra))
        M[:n_base_items, :n_base_cols] = base_M
        for j, row in enumerate(new_rows):
            M[n_base_items + j, :n_base_cols] = row
            start = n_base_cols + j * self.features_per_node
            M[n_base_items + j, start:start + self.features_per_node] = 1.0

        out = object.__new__(HierarchicalEncoder)
        out.nodes = self.nodes
        out.features_per_node = self.features_per_node
        out.include_root_features = self.include_root_features
        out.normalize = self.normalize
        out.seed = self.seed
        out.rng = rng
        out.idx_to_word = list(self.idx_to_word) + new_names
        out.word_to_idx = {w: i for i, w in enumerate(out.idx_to_word)}
        out.feature_matrix = M
        out.embeddings = self._normalize_rows(M) if self.normalize else M.copy()
        out.n_features = M.shape[1]
        out.embedding_dim = M.shape[1]
        out.name_to_node = dict(self.name_to_node)
        out.base_items = list(self.idx_to_word)
        out.new_items = list(new_names)
        out.base_encoder = self
        return out

    def _ancestor_columns(self, node_name: str) -> List[int]:
        """Columns owned by the node and all of its ancestors."""
        idx = self.name_to_node[node_name]
        cols: List[int] = []
        while idx is not None:
            cols.extend(self.nodes[idx]["columns"])
            idx = self.nodes[idx]["parent"]
        return cols

    def _exclusive_columns(self, leaf_indices: Sequence[int]) -> List[int]:
        """Columns set for at least one of these leaves and no leaf outside."""
        leaves = set(leaf_indices)
        cols = []
        for c in range(self.feature_matrix.shape[1]):
            active = set(np.flatnonzero(self.feature_matrix[:, c] > 0).tolist())
            if active and active <= leaves:
                cols.append(c)
        return cols

    def _fill_across_sources(self, row: np.ndarray, source_leaves: Sequence[int],
                             target: float, rng: np.random.Generator) -> np.ndarray:
        """Fill to ``target`` density by taking columns from *distinct* leaves.

        Round-robin across the source leaves rather than sampling a flat pool,
        so the result is guaranteed to be a genuine recombination and can never
        redraw one existing item's exact column set. This is what makes the
        paper's sparrowhawk (small like the sparrow, fierce like the hawk) a new
        item rather than a copy, and it is what separates rung 2 from rung 1.
        """
        row = row.copy()
        per_leaf = {
            leaf: [c for c in self._exclusive_columns([leaf]) if row[c] == 0]
            for leaf in source_leaves
        }
        for cols in per_leaf.values():
            rng.shuffle(cols)
        order = list(source_leaves)
        rng.shuffle(order)
        need = int(round(target - float(np.sum(row > 0))))
        placed, exhausted = 0, False
        while placed < need and not exhausted:
            exhausted = True
            for leaf in order:
                if placed >= need:
                    break
                if per_leaf[leaf]:
                    row[per_leaf[leaf].pop()] = 1.0
                    placed += 1
                    exhausted = False
        return row

    @staticmethod
    def _fill_to_density(row: np.ndarray, pool: Sequence[int], target: float,
                         rng: np.random.Generator) -> np.ndarray:
        """Add columns from ``pool`` until the row has ~``target`` active features."""
        row = row.copy()
        need = int(round(target - float(np.sum(row > 0))))
        avail = [c for c in pool if row[c] == 0]
        if need > 0 and avail:
            take = rng.choice(avail, size=min(need, len(avail)), replace=False)
            row[np.asarray(take, dtype=int)] = 1.0
        return row
