"""Generate the protocol-dissociation tables for the methods section from the
symbolic-suite results of the zoo capacity run.

Both numbers in Table 1 come from the *same* trained model at the *same* list
length (the `length_sweep` series written by
`memval/benchmarks/symbolic_pipeline.py`), so the cued-vs-autoregressive
comparison is within-run and not confounded by training regime:

  - MRR   = `measure_recall_associative`  -- each position probed independently
            with a noisy ground-truth cue (teacher-forced).
  - span  = `memory_span(measure_recall_autoregressive(...))` -- longest prefix
            recalled above 0.75 while the model free-runs on its own output.

Table 2 reports the same span under the three `feedback_mode` settings, which is
the protocol degree of freedom the section declares.

Writes docs/figures/protocol_dissociation_table.md.
"""

import json
import os
import glob

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
# The zoo capacity run: one directory per arm, all from the same checkout.
RESULTS = os.path.join(ROOT, "results", "zoo_capacity_run")
OUT = os.path.join(HERE, "protocol_dissociation_table.md")

# Display names, in the order they should appear. Models absent from RESULTS
# are skipped silently.
MODELS = [
    ("AsymmetricHopfieldNetwork", "AHN"),
    ("ThetaPhaseSequenceNetwork", "theta"),
    ("MultilayerTemporalPCNetwork", "tPC"),
    ("PredictiveRecirculationNetwork", "Chen recirculation"),
    ("OriginalEqPropSequenceNetwork", "EP"),
    ("DTSESNSequenceNetwork", "DTS-ESN"),
]

LENGTHS_SHOWN = [5, 7, 11]


def load(model_dir):
    path = os.path.join(RESULTS, model_dir, "symbolic", "metrics.json")
    if not os.path.exists(path):
        return None
    with open(path) as fh:
        return json.load(fh)


def sweep(doc):
    """Return (lengths, mrr, {mode: spans}) or None if the run has no sweep."""
    s = (doc.get("series") or {}).get("length_sweep")
    if not s or "lengths" not in s:
        return None
    spans = {}
    # `span` is the backward-compatible alias for raw feedback in runs that
    # predate the feedback-mode split; those runs have no l2/quantized series.
    spans["raw"] = s.get("span_raw") or s.get("span")
    for mode in ("l2", "quantized"):
        if s.get("span_" + mode) is not None:
            spans[mode] = s["span_" + mode]
    return s["lengths"], s.get("mrr"), spans


def at(lengths, series, L):
    if not series or L not in lengths:
        return None
    return series[lengths.index(L)]


def fmt(v, digits=2):
    if v is None:
        return "--"
    return f"{v:.{digits}f}" if isinstance(v, float) else str(v)


def main():
    rows1, rows2, missing_modes = [], [], []

    for model_dir, label in MODELS:
        doc = load(model_dir)
        if doc is None:
            continue
        sw = sweep(doc)
        if sw is None:
            continue
        lengths, mrr, spans = sw

        cells = []
        for L in LENGTHS_SHOWN:
            cells.append(fmt(at(lengths, mrr, L)))
            cells.append(fmt(at(lengths, spans.get("raw"), L)))
        rows1.append((label, cells))

        if "quantized" not in spans:
            missing_modes.append(label)
            continue
        rows2.append((
            label,
            [fmt(at(lengths, spans.get(m), 11)) for m in ("raw", "l2", "quantized")],
        ))

    lines = []
    lines.append("<!-- GENERATED by docs/figures/protocol_dissociation_table.py "
                 "-- do not edit by hand. -->")
    lines.append("")

    # ---- Table 1: protocol dissociation -------------------------------------
    head = "| Model |" + "".join(
        f" MRR (L={L}) | Span (L={L}) |" for L in LENGTHS_SHOWN)
    sep = "|---|" + "---|" * (2 * len(LENGTHS_SHOWN))
    lines += ["**Table 1.** Cued MRR vs. free-running span, same trained model, "
              "raw feedback. Span is the longest prefix recalled above 0.75.",
              "", head, sep]
    for label, cells in rows1:
        lines.append(f"| {label} | " + " | ".join(cells) + " |")
    lines.append("")

    # ---- Table 2: feedback-mode sensitivity ---------------------------------
    lines += ["**Table 2.** Free-running span at L=11 under the three feedback "
              "modes. `quantized` snaps each prediction to its decoded symbol "
              "before re-injection; L-1 = 10 is a perfect run.",
              "",
              "| Model | raw | L2-normalized | quantized |",
              "|---|---|---|---|"]
    for label, cells in rows2:
        lines.append(f"| {label} | " + " | ".join(cells) + " |")
    if missing_modes:
        lines += ["", "> Runs predating the feedback-mode split (raw only): "
                  + ", ".join(missing_modes) + "."]
    lines.append("")

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))
    print("\n".join(lines))
    print(f"\n[written] {OUT}")


if __name__ == "__main__":
    main()
